version: "3.8"
services:
  api:
    container_name: api
    build: ../fastify
    links:
      - db
    environment:
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
    volumes:
      - ../fastify:/usr/src/app
  db:
    container_name: db
    build: ../db
    environment:
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ../db:/usr/src/app
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../html:/www/data/html
      - ../log/access.log:/var/log/nginx/access.log
  monitor:
    container_name: monitor
    build: ../monitor
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${RESUME_DB_PORT}
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
      - RESUME_PROJECT_ID=${RESUME_PROJECT_ID}
    links:
      - api
      - db
      - nginx
    volumes:
      - ../log/access.log:/var/log/nginx/access.log
      - ../monitor:/monitor
    command: tail -f /etc/issue
volumes:
  db:
    driver: local
