version: "3.8"
services:
  pg_default:
    # These vars are set in ./.env e.g:
    # RESUME_DB_HOST=dbhost.com
    # RESUME_DB_PORT=12345
    # The env file can be overridden by shell env vars
    environment:
      - POSTGRES_HOST=${RESUME_DB_HOST}
      - POSTGRES_PORT=${RESUME_DB_PORT}
      - POSTGRES_DB_NAME=${RESUME_DB_NAME}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
  api:
    extends:
      service: pg_default
    container_name: api
    build: ../fastify
    restart: always
    links:
      - db
      - cache
    volumes:
      - ../fastify:/usr/src/app
  db:
    extends:
      service: pg_default
    container_name: db
    build: ../db
    restart: always
    ports:
      - ${RESUME_DB_PORT}:${RESUME_DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
      - ../db:/usr/src/app
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    links:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/log/nginx/:/var/log/nginx/
  monitor:
    extends:
      service: pg_default
    container_name: monitor
    build: ../monitor
    restart: always
    environment:
      - RESUME_GCLOUD_PROJECT_ID=${RESUME_GCLOUD_PROJECT_ID}
      - NGINX_LOG_PATH=/var/log/nginx
    links:
      - api
      - db
      - nginx
    volumes:
      - /var/log/nginx/:/var/log/nginx/
      - ../monitor:/monitor
    command: tail -f /etc/issue # Arbitrary command to keep container running
  cache:
    image: redis
    container_name: cache
    restart: always
volumes:
  db:
    driver: local
