version: "3.8"
services:
  pg_default:
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${RESUME_DB_PORT}
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
  api:
    extends:
      service: pg_default
    container_name: api
    build: ../fastify
    restart: always
    links:
      - db
      - cache
    volumes:
      - ../fastify:/usr/src/app
  db:
    extends:
      service: pg_default
    container_name: db
    build: ../db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ../db:/usr/src/app
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    links:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../react-ui/build:/www/data/html
      - ../log/access.log:/var/log/nginx/access.log
  monitor:
    extends:
      service: pg_default
    container_name: monitor
    build: ../monitor
    restart: always
    environment:
      - RESUME_PROJECT_ID=${RESUME_PROJECT_ID}
      - NGINX_LOG_PATH=/var/log/nginx
    links:
      - api
      - db
      - nginx
    volumes:
      - ../log/access.log:/var/log/nginx/access.log
      - ../monitor:/monitor
    command: tail -f /etc/issue # Arbitrary command to keep container running
  cache:
    image: redis
    container_name: cache
    restart: always
volumes:
  db:
    driver: local
