version: "3.8"
services:
  api:
    extends:
      file: base.yml
      service: api
    environment:
      - PRODUCTION=true
  db:
    container_name: db
    extends:
      file: base.yml
      service: db
    volumes:
      - ../config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.confg
      - ../config/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ../ssl/server.crt:/var/lib/postgresql/data/server.crt
      - ../ssl/server.key:/var/lib/postgresql/data/server.key
  nginx:
    extends:
      file: base.yml
      service: nginx
    volumes:
      - ../config/nginx-production.conf:/etc/nginx/nginx.conf
      - ../ssl/fullchain.pem:/ssl/cert.pem
      - ../ssl/privkey.pem:/ssl/key.pem
  monitor:
    extends:
      file: base.yml
      service: monitor
volumes:
  db:
    driver: local
