version: "3.8"
services:
  api:
    container_name: api
    build: ../fastify
    links:
      - db
    environment:
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
    volumes:
      - ../fastify:/usr/src/app
  db:
    container_name: db
    build: ../db
    environment:
      - POSTGRES_DB=${RESUME_DB}
      - POSTGRES_USER=${RESUME_DB_USER}
      - POSTGRES_PASSWORD=${RESUME_DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ../db:/usr/src/app
      - db:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:latest
    links:
      - api
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../html:/www/data/html
      - ../config/nginx-production.conf:/etc/nginx/nginx.conf
      - ../ssl/fullchain.pem:/ssl/cert.pem
      - ../ssl/privkey.pem:/ssl/key.pem
volumes:
  db:
    driver: local
